services:
  api:
    image: mouther201/sitshift:latest
    ports:
      - "8000:5000"
    environment:
      - APP_ENV=local
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
